{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (import ../lib/option.nix lib) mkOption;
  cfg = config.nixie.backups;
  root = toString config.nixie.data.root;
  guestsLib = import ../lib/guests.nix { inherit lib; };
in
{
  options.nixie.backups = {
    enable = mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Back up the state directory and every guest's backup paths with restic
        on a schedule. Costs storage at the repository and some disk activity.
      '';
      nixieUi = {
        section = "services";
        order = 0;
      };
    };
    repository = mkOption {
      type = lib.types.str;
      default = "";
      example = "sftp:backup@host:/srv/restic";
      description = "Where backups go, as a restic repository URL.";
      nixieUi = {
        section = "services";
        order = 1;
      };
    };
    passwordFile = mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "File holding the repository password.";
    };
    environmentFile = mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "File with credentials for the repository's storage, if it needs any.";
    };
    schedule = mkOption {
      type = lib.types.str;
      default = "daily";
      description = "How often to back up.";
      nixieUi = {
        section = "services";
        order = 2;
      };
    };
    excludes = mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Patterns left out of backups.";
    };
    keep = {
      daily = mkOption {
        type = lib.types.int;
        default = 7;
        description = "Daily snapshots to keep.";
      };
      weekly = mkOption {
        type = lib.types.int;
        default = 4;
        description = "Weekly snapshots to keep.";
      };
      monthly = mkOption {
        type = lib.types.int;
        default = 6;
        description = "Monthly snapshots to keep.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.repository != "" && cfg.passwordFile != null;
        message = "nixie.backups needs a repository and a passwordFile";
      }
    ];
    services.restic.backups.nixie = {
      inherit (cfg) repository passwordFile environmentFile;
      initialize = true;
      paths = lib.unique (
        [ "${root}/state" ]
        ++ guestsLib.backupPaths config.nixie.guests
        ++ lib.optional config.nixie.data.mediaBackup "${root}/media"
      );
      # cache/ is re-fetchable by definition and Incus's own database is
      # regenerated by apply; neither belongs in a backup.
      exclude = [
        "${root}/cache"
        "/var/lib/incus/database"
      ]
      ++ cfg.excludes;
      timerConfig = {
        OnCalendar = cfg.schedule;
        Persistent = true;
      };
      pruneOpts = [
        "--keep-daily ${toString cfg.keep.daily}"
        "--keep-weekly ${toString cfg.keep.weekly}"
        "--keep-monthly ${toString cfg.keep.monthly}"
      ];
    };
    # `nixie restore <snapshot>` puts state/ back from the repository.
    environment.systemPackages = [
      (pkgs.writeShellApplication {
        name = "nixie-restore";
        text = ''
          snap=''${1:-latest}
          exec restic-nixie restore "$snap" --target / "''${@:2}"
        '';
      })
    ];
  };
}
