{
 "title": "GPU",
 "tags": [ "nixie" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "nvidia_smi_temperature_gpu", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "nvidia_smi_power_draw_watts", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nvidia_smi_memory_used_bytes", "legendFormat": "{{uuid}}" }
   ]
  }
 ]
}