{
 "title": "Guest",
 "tags": [ "nixie" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "guest",
    "query": "label_values(incus_cpu_seconds_total, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(incus_cpu_seconds_total{name=~\"$guest\"}[5m])",
     "legendFormat": "{{name}} {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "incus_memory_MemTotal_bytes{name=~\"$guest\"} - incus_memory_MemAvailable_bytes{name=~\"$guest\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(incus_network_receive_bytes_total{name=~\"$guest\"}[5m])",
     "legendFormat": "{{name}} {{device}} rx"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(incus_disk_read_bytes_total{name=~\"$guest\"}[5m]) + rate(incus_disk_written_bytes_total{name=~\"$guest\"}[5m])",
     "legendFormat": "{{name}} {{device}}"
    }
   ]
  }
 ]
}