-- Generated by Nixie from nixie.desktop.*; edit ~/.config/hypr/local.lua instead.
local home = os.getenv("HOME") or "/root"
local function read(p)
  local f = io.open(p, "r")
  if not f then return nil end
  local s = f:read("a"); f:close()
  return (s:gsub("%s+$", ""))
end
local finish = read(home .. "/.config/nixie/finish") or read("/etc/nixie/desktop/default-finish") or @finish@
local tokens = read("/etc/nixie/desktop/" .. finish .. "/tokens.json") or ""
local function tok(k, d) return tokens:match('"' .. k .. '"%s*:%s*"(#%x+)"') or d end
local accent = read(home .. "/.config/nixie/accent") or tok("brand2", "#7ebae4")
local function rgb(h) return "rgb(" .. h:sub(2) .. ")" end
local function rgba(h, a) return "rgba(" .. h:sub(2) .. a .. ")" end

@monitors@
hl.env("XCURSOR_THEME", @cursorTheme@)
hl.env("XCURSOR_SIZE", @cursorSize@)
hl.env("HYPRCURSOR_SIZE", @cursorSize@)
hl.env("NIXIE_FINISH", finish)

hl.config({
  general = {
    gaps_in = @gapsIn@,
    gaps_out = @gapsOut@,
    border_size = @borderSize@,
    col = {
      active_border = { colors = { rgb(accent), rgb(tok("brand", "#5277c3")) }, angle = 45 },
      inactive_border = rgb(tok("line", "#383e46")),
    },
    resize_on_border = true,
    allow_tearing = false,
    layout = "dwindle",
  },
  decoration = {
    rounding = @rounding@,
    rounding_power = 3,
    active_opacity = 1.0,
    inactive_opacity = 0.97,
    shadow = { enabled = true, range = 30, render_power = 3, color = rgba(tok("s2", "#181b1e"), "8c") },
    blur = { enabled = @blur@, size = 8, passes = 3, noise = 0.02, vibrancy = 0.17, popups = true },
  },
  dwindle = { preserve_split = true },
  misc = { disable_hyprland_logo = true, disable_splash_rendering = true, focus_on_activate = true, font_family = @uiFont@ },
  input = {
    kb_layout = @kbLayout@,
    kb_variant = @kbVariant@,
    follow_mouse = 1,
    touchpad = { natural_scroll = true },
  },
})
@anim@
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Performance mode: a fullscreen window or a game drops blur and motion.
hl.window_rule({ name = "perf-fullscreen", match = { fullscreen = true }, no_blur = true, no_anim = true, idle_inhibit = "fullscreen" })
hl.window_rule({ name = "perf-games", match = { class = "^(steam_app_.*|gamescope)$" }, immediate = true, no_blur = true })
hl.window_rule({ name = "no-maximize", match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ name = "float-utilities", match = { class = "^(pavucontrol|org\\.pulseaudio\\.pavucontrol|blueman-manager|nm-connection-editor|xdg-desktop-portal-gtk)$" }, float = true, center = true, size = "720 520" })
hl.window_rule({ name = "pip", match = { title = "^(Picture-in-Picture|Picture in picture)$" }, float = true, pin = true })
hl.layer_rule({ name = "shell-blur", match = { namespace = "^nixie-shell$" }, blur = true, ignore_alpha = 0.3 })
hl.layer_rule({ name = "lock-anim", match = { namespace = "^hyprlock$" }, no_anim = true })

@execBinds@
@mediaKeys@
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = 0 }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = 1 }))
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + P", hl.dsp.window.pin())
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
for key, dir in pairs({ H = "left", L = "right", K = "up" }) do
  hl.bind("SUPER + " .. key, hl.dsp.focus({ direction = dir }))
  hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ direction = dir }))
end
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
for key, dir in pairs({ left = "left", right = "right", up = "up", down = "down" }) do
  hl.bind("SUPER + " .. key, hl.dsp.focus({ direction = dir }))
end
for i = 1, 10 do
  local key = i % 10
  hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
  hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("scratch"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratch" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.on("hyprland.start", function()
  hl.exec_cmd("nixie-shell wallpaper restore")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("nixie-shell finish apply")
  @nightLight@
  @autostart@
end)

-- Your tweaks: ~/.config/hypr/local.lua, loaded last, no rebuild needed.
pcall(require, "local")
