add_newline = true
format = "$directory$git_branch$git_status$nix_shell$cmd_duration$line_break$character"
[character]
success_symbol = "[›](bold @brand2@)"
error_symbol = "[›](bold @err@)"
[directory]
style = "bold @ink@"
truncation_length = 3
[git_branch]
style = "@mem@"
symbol = " "
[git_status]
style = "@hot@"
[nix_shell]
symbol = " "
style = "@net@"
[cmd_duration]
style = "@muted@"
